name: Deploy to Huawei Cloud CAE

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Deploy Component
        uses: lemrex/Upgrade-CAE-component@1.0.6
        with:
          project_id: ${{ secrets.PROJECT_ID }}
          environment_name: ralf
          app_name: "api"
          component_name: "vuejs"
          version: "1.0.5"
          accessKey: ${{ secrets.ACCESSKEY }}
          secretKey: ${{ secrets.SECRET_KEY }}
          region: "af-south-1"
