name: Deploy to Huawei Cloud CAE

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Deploy Component
        uses: lemrex/Upgrade-CAE-component@v1.0.0
        with:
          project_id: ${{ secrets.PROJECT_ID }}
          environment_name: demo
          app_name: "test"
          component_name: "vuejs"
          version: "1.0.1"
          accessKey: ${{ secrets.ACCESSKEY }}
          secretKey: ${{ secrets.SECRET_KEY }}
          region: "af-south-1"
          # enterprise_project_id: "3e7cb44b-4b49-43b5-93df-d78f8a24e2dc"
